from source.consts.questionnaires_names import Questionnaire


Reverse_Items = {
    Questionnaire.cshq_f: ['bedtime_2_f', 'bedtime_3_f', 'bedtime_4_f', 'duration_1_f', 'duration_2_f',
                           'night_wake_1_f'],
    Questionnaire.cshq_m: ['bedtime_2_m', 'bedtime_3_m', 'bedtime_4_m', 'duration_1_m', 'duration_2_m',
                           'night_wake_1_m'],
    Questionnaire.ders: ['ders_1',
                 'ders_2',
                 'ders_6',
                 'ders_7',
                 'ders_8',
                 'ders_10',
                 'ders_17',
                 'ders_20',
                 'ders_22',
                 'ders_24',
                 'ders_34'],
    Questionnaire.ders_p_m: ['ders_1_p_m',
                             'ders_2_p_m',
                             'ders_6_p_m',
                             'ders_7_p_m',
                             'ders_8_p_m',
                             'ders_10_p_m',
                             'ders_17_p_m',
                             'ders_20_p_m',
                             'ders_22_p_m',
                             'ders_24_p_m',
                             'ders_34_p_m'
                             ],
    Questionnaire.ders_p_f: ['ders_1_p_f',
                             'ders_2_p_f',
                             'ders_6_p_f',
                             'ders_7_p_f',
                             'ders_8_p_f',
                             'ders_10_p_f',
                             'ders_17_p_f',
                             'ders_20_p_f',
                             'ders_22_p_f',
                             'ders_24_p_f',
                             'ders_34_p_f'
                             ],
    Questionnaire.ecr_m: ['ecr_3_m', 'ecr_15_m', 'ecr_19_m', 'ecr_22_m', 'ecr_25_m', 'ecr_27_m', 'ecr_29_m', 'ecr_31_m',
                          'ecr_33_m', 'ecr_35_m'],
    Questionnaire.ecr_f: ['ecr_3_f', 'ecr_15_f', 'ecr_19_f', 'ecr_22_f', 'ecr_25_f', 'ecr_27_f', 'ecr_29_f', 'ecr_31_f',
                          'ecr_33_f', 'ecr_35_f'],
    Questionnaire.erc_rc: ['erc_rc_10', 'erc_rc_11', 'erc_rc_12'],

    Questionnaire.inq: ['inq_7', 'inq_8', 'inq_10', 'inq_13', 'inq_14', 'inq_15'],

    Questionnaire.sdq: ['sdq_7', 'sdq_11', 'sdq_14', 'sdq_21', 'sdq_25'],
    Questionnaire.sdq_parents_f: ['sdq_7_parents_f', 'sdq_11_parents_f', 'sdq_14_parents_f', 'sdq_21_parents_f',
                                  'sdq_25_parents_f'],
    Questionnaire.sdq_parents_m: ['sdq_7_parents_m', 'sdq_11_parents_m', 'sdq_14_parents_m', 'sdq_21_parents_m',
                                  'sdq_25_parents_m'],

    Questionnaire.trq_sf_maris_clin: ['trq_sf_maris_1_clin', 'trq_sf_maris_2_clin',
                                      'trq_sf_maris_3_clin', 'trq_sf_maris_4_clin'],
    Questionnaire.trq_sf_maris_stu: ['trq_sf_maris_1_stu', 'trq_sf_maris_2_stu',
                                     'trq_sf_maris_3_stu', 'trq_sf_maris_4_stu'],

    Questionnaire.wai: ['wai_4', 'wai_10'],
    Questionnaire.wai_immirisk_clin: ['wai_t_immi_4_clin', 'wai_t_immi_10_clin'],
}
